id = "monokai-vibrant-amped"
name = "monokai vibrant amped"
version = "0.0.1"
schema_version = 1
authors = ["Chadderbox"]
description = "A version of Monokai Vibrant Amped, but for Zed!"
repository = "https://github.com/ceebox/monokai-vibrant-amped-zed"
